name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: "If the same issue occurs in the Fabric version of Immersive Portals, please open an issue to the Fabric version repo:  https://github.com/iPortalTeam/ImmersivePortalsMod/issues"
  - type: markdown
    attributes:
      value: "To know whether it's a mod compatibility issue, please remove all other mods and keep only Immersive Portals mod, backup your world, and then test again whether the issue occurs. Thanks for cooperation. \nIf Immersive Portals mod makes other mod's functionality break, you don't need to test it, simply select No below."
  - type: dropdown
    id: only_immptl
    attributes:
      label: According to your testing, does the issue occur with ONLY Immersive Portals mod?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Please tell how to reproduce the issue.
      value: "Describe the issue."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Post the log here
      description: The log is `game_directory/logs/latest.log`. The log provides useful information (including the mod list) for debugging the issue.
      render: shell
